use_frameworks!

platform :ios, '9.0'

target 'AmzurMobileFramworks_Example' do
  pod 'AmzurMobileFramworks', :path => '../'

  target 'AmzurMobileFramworks_Tests' do
    inherit! :search_paths

    
  end
end
